apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" .}} 
  namespace: {{  .Values.namespace }} 
  labels:
    app: {{ template "fullname" .}}
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{ if .Values.awsRole }}iam.amazonaws.com/role: {{ .Values.awsRole }}{{ end }}
      labels:
        app: {{ template "fullname" .}}
    spec:
      initContainers: 
      - name: copy-fluentd-config
        image: "{{.Values.busybox.repository}}:{{.Values.busybox.tag}}"
        command: ['sh', '-c', 'cp /config-volume/* /etc/fluentd']
        volumeMounts:
          - name: config-volume
            mountPath: /config-volume
          - name: config
            mountPath: /etc/fluentd
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: AWS_REGION
          value: {{ .Values.awsRegion }}
        - name: BUCKET_NAME
          value: {{ .Values.bucketName }}
        securityContext:
          privileged: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluentd/etc
        - name: config-volume
          mountPath: /config-volume
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}
